import type { Metadata } from "next";

import { VinelandLayout } from "@/src/ui/components/templates";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <VinelandLayout>
      {children}
    </VinelandLayout>
  );
}
